services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: kidgpt
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
  kidgpt:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: kidgpt
      FERNET_KEY: ${FERNET_KEY}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}

volumes:
  mysql_data:
